👷 (ci): Upgrade build workflow to handle cache and failures

diff --git a/.github/workflows/ci-tuist-build.yml b/.github/workflows/ci-tuist-build.yml
--- a/.github/workflows/ci-tuist-build.yml
+++ b/.github/workflows/ci-tuist-build.yml
@@ -25,6 +25,8 @@ env:
   TUIST_TURN_OFF_LINTERS: TRUE
   TUIST_GENERATE_EXAMPLE_TARGETS: TRUE
   TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG: FALSE
+  TUIST_GENERATE_L10N_SCHEMES: FALSE
+  TUIST_GENERATE_EXAMPLE_TARGETS: TRUE
 
 jobs:
   build:
@@ -51,21 +53,78 @@ jobs:
           TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
           TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
           TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
           TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
           tuist install
+
+      - name: tuist cache
+        run: |
+          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
+          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
+          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
+          tuist cache
 
       - name: tuist generate
         run: |
           TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
           TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
           TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
           TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
           tuist generate --no-open
 
       - name: tuist build
+        id: tuist_build
         run: |
           TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
           TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
           TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
           TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
           tuist build
+        continue-on-error: true
+
+      - name: tuist clean + build
+        id: tuist_clean_build
+        run: |
+          make clean
+
+          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
+          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
+          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
+          tuist install
+
+          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
+          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
+          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
+          tuist cache
+
+          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
+          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
+          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
+          tuist generate --no-open
+
+          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
+          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
+          TUIST_GENERATE_L10N_SCHEMES=${{ env.TUIST_GENERATE_L10N_SCHEMES }} \
+          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
+          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
+          tuist build
+        continue-on-error: true
+
+      - name: Finalize Workflow
+        if: steps.tuist_build.outcome == 'failure' && steps.tuist_clean_build.outcome == 'failure'
+        run: |
+          echo "We failed to build the project"
+          exit 1
